// Generated by psc-bundle 0.7.6.1
var PS = { };
(function(exports) {
  /* global exports */
  "use strict";

  // module Control.Monad.Eff

  exports.returnE = function (a) {
    return function () {
      return a;
    };
  };

  exports.bindE = function (a) {
    return function (f) {
      return function () {
        return f(a())();
      };
    };
  };
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  //- Bounded --------------------------------------------------------------------

  exports.topInt = 2147483647;
  exports.bottomInt = -2147483648;

  //- Show -----------------------------------------------------------------------

  exports.showIntImpl = function (n) {
    return n.toString();
  };
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Prelude"];
  var Functor = function (map) {
      this.map = map;
  };
  var Apply = function (__superclass_Prelude$dotFunctor_0, apply) {
      this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
      this.apply = apply;
  };
  var Applicative = function (__superclass_Prelude$dotApply_0, pure) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.pure = pure;
  };
  var Bind = function (__superclass_Prelude$dotApply_0, bind) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.bind = bind;
  };
  var Monad = function (__superclass_Prelude$dotApplicative_0, __superclass_Prelude$dotBind_1) {
      this["__superclass_Prelude.Applicative_0"] = __superclass_Prelude$dotApplicative_0;
      this["__superclass_Prelude.Bind_1"] = __superclass_Prelude$dotBind_1;
  };
  var Semiring = function (add, mul, one, zero) {
      this.add = add;
      this.mul = mul;
      this.one = one;
      this.zero = zero;
  };
  var Ring = function (__superclass_Prelude$dotSemiring_0, sub) {
      this["__superclass_Prelude.Semiring_0"] = __superclass_Prelude$dotSemiring_0;
      this.sub = sub;
  };
  var Bounded = function (bottom, top) {
      this.bottom = bottom;
      this.top = top;
  };
  var Show = function (show) {
      this.show = show;
  };
  var zero = function (dict) {
      return dict.zero;
  };            
  var top = function (dict) {
      return dict.top;
  };
  var sub = function (dict) {
      return dict.sub;
  };
  var $minus = function (__dict_Ring_0) {
      return sub(__dict_Ring_0);
  };                                                 
  var showInt = new Show($foreign.showIntImpl);
  var show = function (dict) {
      return dict.show;
  };                  
  var pure = function (dict) {
      return dict.pure;
  };
  var $$return = function (__dict_Applicative_2) {
      return pure(__dict_Applicative_2);
  };
  var otherwise = true;
  var one = function (dict) {
      return dict.one;
  };
  var mul = function (dict) {
      return dict.mul;
  };
  var map = function (dict) {
      return dict.map;
  };
  var $less$dollar$greater = function (__dict_Functor_5) {
      return map(__dict_Functor_5);
  }; 
  var boundedInt = new Bounded($foreign.bottomInt, $foreign.topInt);
  var bottom = function (dict) {
      return dict.bottom;
  };
  var bind = function (dict) {
      return dict.bind;
  };
  var $greater$greater$eq = function (__dict_Bind_24) {
      return bind(__dict_Bind_24);
  }; 
  var apply = function (dict) {
      return dict.apply;
  };
  var $less$times$greater = function (__dict_Apply_25) {
      return apply(__dict_Apply_25);
  };
  var liftA1 = function (__dict_Applicative_26) {
      return function (f) {
          return function (a) {
              return $less$times$greater(__dict_Applicative_26["__superclass_Prelude.Apply_0"]())(pure(__dict_Applicative_26)(f))(a);
          };
      };
  };
  var ap = function (__dict_Monad_30) {
      return function (f) {
          return function (a) {
              return bind(__dict_Monad_30["__superclass_Prelude.Bind_1"]())(f)(function (_2) {
                  return bind(__dict_Monad_30["__superclass_Prelude.Bind_1"]())(a)(function (_1) {
                      return $$return(__dict_Monad_30["__superclass_Prelude.Applicative_0"]())(_2(_1));
                  });
              });
          };
      };
  }; 
  var add = function (dict) {
      return dict.add;
  };
  var $plus = function (__dict_Semiring_31) {
      return add(__dict_Semiring_31);
  };
  exports["Show"] = Show;
  exports["Bounded"] = Bounded;
  exports["Ring"] = Ring;
  exports["Semiring"] = Semiring;
  exports["Monad"] = Monad;
  exports["Bind"] = Bind;
  exports["Applicative"] = Applicative;
  exports["Apply"] = Apply;
  exports["Functor"] = Functor;
  exports["show"] = show;
  exports["bottom"] = bottom;
  exports["top"] = top;
  exports["-"] = $minus;
  exports["sub"] = sub;
  exports["+"] = $plus;
  exports["one"] = one;
  exports["mul"] = mul;
  exports["zero"] = zero;
  exports["add"] = add;
  exports["ap"] = ap;
  exports["return"] = $$return;
  exports[">>="] = $greater$greater$eq;
  exports["bind"] = bind;
  exports["liftA1"] = liftA1;
  exports["pure"] = pure;
  exports["apply"] = apply;
  exports["<$>"] = $less$dollar$greater;
  exports["map"] = map;
  exports["otherwise"] = otherwise;
  exports["boundedInt"] = boundedInt;
  exports["showInt"] = showInt;;
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Control.Monad.Eff"];
  var Prelude = PS["Prelude"];     
  var monadEff = new Prelude.Monad(function () {
      return applicativeEff;
  }, function () {
      return bindEff;
  });
  var bindEff = new Prelude.Bind(function () {
      return applyEff;
  }, $foreign.bindE);
  var applyEff = new Prelude.Apply(function () {
      return functorEff;
  }, Prelude.ap(monadEff));
  var applicativeEff = new Prelude.Applicative(function () {
      return applyEff;
  }, $foreign.returnE);
  var functorEff = new Prelude.Functor(Prelude.liftA1(applicativeEff));
  exports["functorEff"] = functorEff;
  exports["applyEff"] = applyEff;
  exports["applicativeEff"] = applicativeEff;
  exports["bindEff"] = bindEff;
  exports["monadEff"] = monadEff;;
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  exports.unsafeQuerySelector = function (selector) {
    return function (src) {
      return function () {
        return src.querySelector(selector);
      };
    };
  };

  exports.unsafeSetTextContent = function (value) {
    return function (src) {
      return function () {
        src.textContent = value;
        return {};
      };
    };
  };
 
})(PS["Data.DOM.Simple.Unsafe.Element"] = PS["Data.DOM.Simple.Unsafe.Element"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Unsafe.Element"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var DOM_Node_Types = PS["DOM.Node.Types"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Unsafe_Utils = PS["Data.DOM.Simple.Unsafe.Utils"];
  exports["unsafeSetTextContent"] = $foreign.unsafeSetTextContent;
  exports["unsafeQuerySelector"] = $foreign.unsafeQuerySelector;;
 
})(PS["Data.DOM.Simple.Unsafe.Element"] = PS["Data.DOM.Simple.Unsafe.Element"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.DOM.Simple.Unsafe.Window

  exports.unsafeDocument = function (win) {
    return function () {
      return win.document;
    };
  };
 
})(PS["Data.DOM.Simple.Unsafe.Window"] = PS["Data.DOM.Simple.Unsafe.Window"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Unsafe.Window"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Document = PS["Data.DOM.Simple.Document"];
  exports["unsafeDocument"] = $foreign.unsafeDocument;;
 
})(PS["Data.DOM.Simple.Unsafe.Window"] = PS["Data.DOM.Simple.Unsafe.Window"] || {});
(function(exports) {
  /* global exports, window */
  "use strict";

  // module Data.DOM.Simple.Window

  exports.globalWindow = window;
 
})(PS["Data.DOM.Simple.Window"] = PS["Data.DOM.Simple.Window"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Extend = PS["Control.Extend"];
  var Control_MonadPlus = PS["Control.MonadPlus"];
  var Control_Plus = PS["Control.Plus"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Monoid = PS["Data.Monoid"];     
  var Nothing = (function () {
      function Nothing() {

      };
      Nothing.value = new Nothing();
      return Nothing;
  })();
  var Just = (function () {
      function Just(value0) {
          this.value0 = value0;
      };
      Just.create = function (value0) {
          return new Just(value0);
      };
      return Just;
  })();
  exports["Nothing"] = Nothing;
  exports["Just"] = Just;;
 
})(PS["Data.Maybe"] = PS["Data.Maybe"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Window"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Unsafe_Window = PS["Data.DOM.Simple.Unsafe.Window"];
  var Data_DOM_Simple_Document = PS["Data.DOM.Simple.Document"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Array = PS["Data.Array"];
  var Data_String = PS["Data.String"];
  exports["globalWindow"] = $foreign.globalWindow;;
 
})(PS["Data.DOM.Simple.Window"] = PS["Data.DOM.Simple.Window"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  exports.nowImpl = function (ctor) {
    return function () {
      return ctor(new Date());
    };
  };
 
})(PS["Data.Date"] = PS["Data.Date"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Maybe.Unsafe

  exports.unsafeThrow = function (msg) {
    throw new Error(msg);
  };
 
})(PS["Data.Maybe.Unsafe"] = PS["Data.Maybe.Unsafe"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.Maybe.Unsafe"];
  var Prelude = PS["Prelude"];
  var Data_Maybe = PS["Data.Maybe"];     
  var fromJust = function (_0) {
      if (_0 instanceof Data_Maybe.Just) {
          return _0.value0;
      };
      if (_0 instanceof Data_Maybe.Nothing) {
          return $foreign.unsafeThrow("Data.Maybe.Unsafe.fromJust called on Nothing");
      };
      throw new Error("Failed pattern match at Data.Maybe.Unsafe line 10, column 1 - line 11, column 1: " + [ _0.constructor.name ]);
  };
  exports["fromJust"] = fromJust;;
 
})(PS["Data.Maybe.Unsafe"] = PS["Data.Maybe.Unsafe"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_Char = PS["Data.Char"];
  var Data_Either = PS["Data.Either"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_Unsafe = PS["Data.Maybe.Unsafe"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Unfoldable = PS["Data.Unfoldable"];
  var Enum = function (__superclass_Prelude$dotBounded_0, cardinality, fromEnum, pred, succ, toEnum) {
      this["__superclass_Prelude.Bounded_0"] = __superclass_Prelude$dotBounded_0;
      this.cardinality = cardinality;
      this.fromEnum = fromEnum;
      this.pred = pred;
      this.succ = succ;
      this.toEnum = toEnum;
  };
  var toEnum = function (dict) {
      return dict.toEnum;
  };
  var succ = function (dict) {
      return dict.succ;
  };
  var pred = function (dict) {
      return dict.pred;
  };                               
  var fromEnum = function (dict) {
      return dict.fromEnum;
  };
  var defaultSucc = function (toEnum$prime) {
      return function (fromEnum$prime) {
          return function (a) {
              return toEnum$prime(fromEnum$prime(a) + 1 | 0);
          };
      };
  };
  var defaultPred = function (toEnum$prime) {
      return function (fromEnum$prime) {
          return function (a) {
              return toEnum$prime(fromEnum$prime(a) - 1);
          };
      };
  };                                                                                                                
  var cardinality = function (dict) {
      return dict.cardinality;
  };
  exports["Enum"] = Enum;
  exports["defaultPred"] = defaultPred;
  exports["defaultSucc"] = defaultSucc;
  exports["toEnum"] = toEnum;
  exports["succ"] = succ;
  exports["pred"] = pred;
  exports["fromEnum"] = fromEnum;
  exports["cardinality"] = cardinality;;
 
})(PS["Data.Enum"] = PS["Data.Enum"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.Date"];
  var Global = PS["Global"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_Enum = PS["Data.Enum"];
  var Data_Function = PS["Data.Function"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Time = PS["Data.Time"];     
  var Year = function (x) {
      return x;
  };
  var January = (function () {
      function January() {

      };
      January.value = new January();
      return January;
  })();
  var February = (function () {
      function February() {

      };
      February.value = new February();
      return February;
  })();
  var March = (function () {
      function March() {

      };
      March.value = new March();
      return March;
  })();
  var April = (function () {
      function April() {

      };
      April.value = new April();
      return April;
  })();
  var May = (function () {
      function May() {

      };
      May.value = new May();
      return May;
  })();
  var June = (function () {
      function June() {

      };
      June.value = new June();
      return June;
  })();
  var July = (function () {
      function July() {

      };
      July.value = new July();
      return July;
  })();
  var August = (function () {
      function August() {

      };
      August.value = new August();
      return August;
  })();
  var September = (function () {
      function September() {

      };
      September.value = new September();
      return September;
  })();
  var October = (function () {
      function October() {

      };
      October.value = new October();
      return October;
  })();
  var November = (function () {
      function November() {

      };
      November.value = new November();
      return November;
  })();
  var December = (function () {
      function December() {

      };
      December.value = new December();
      return December;
  })();
  var DateTime = function (x) {
      return x;
  }; 
  var semiringYear = new Prelude.Semiring(function (_11) {
      return function (_12) {
          return _11 + _12 | 0;
      };
  }, function (_13) {
      return function (_14) {
          return _13 * _14 | 0;
      };
  }, 1, 0);
  var ringYear = new Prelude.Ring(function () {
      return semiringYear;
  }, function (_15) {
      return function (_16) {
          return _15 - _16;
      };
  });
  var now = $foreign.nowImpl(DateTime);
  var monthToEnum = function (_3) {
      if (_3 === 0) {
          return new Data_Maybe.Just(January.value);
      };
      if (_3 === 1) {
          return new Data_Maybe.Just(February.value);
      };
      if (_3 === 2) {
          return new Data_Maybe.Just(March.value);
      };
      if (_3 === 3) {
          return new Data_Maybe.Just(April.value);
      };
      if (_3 === 4) {
          return new Data_Maybe.Just(May.value);
      };
      if (_3 === 5) {
          return new Data_Maybe.Just(June.value);
      };
      if (_3 === 6) {
          return new Data_Maybe.Just(July.value);
      };
      if (_3 === 7) {
          return new Data_Maybe.Just(August.value);
      };
      if (_3 === 8) {
          return new Data_Maybe.Just(September.value);
      };
      if (_3 === 9) {
          return new Data_Maybe.Just(October.value);
      };
      if (_3 === 10) {
          return new Data_Maybe.Just(November.value);
      };
      if (_3 === 11) {
          return new Data_Maybe.Just(December.value);
      };
      return Data_Maybe.Nothing.value;
  };
  var monthFromEnum = function (_4) {
      if (_4 instanceof January) {
          return 0;
      };
      if (_4 instanceof February) {
          return 1;
      };
      if (_4 instanceof March) {
          return 2;
      };
      if (_4 instanceof April) {
          return 3;
      };
      if (_4 instanceof May) {
          return 4;
      };
      if (_4 instanceof June) {
          return 5;
      };
      if (_4 instanceof July) {
          return 6;
      };
      if (_4 instanceof August) {
          return 7;
      };
      if (_4 instanceof September) {
          return 8;
      };
      if (_4 instanceof October) {
          return 9;
      };
      if (_4 instanceof November) {
          return 10;
      };
      if (_4 instanceof December) {
          return 11;
      };
      throw new Error("Failed pattern match at Data.Date line 197, column 1 - line 198, column 1: " + [ _4.constructor.name ]);
  };
  var boundedMonth = new Prelude.Bounded(January.value, December.value);
  var enumMonth = new Data_Enum.Enum(function () {
      return boundedMonth;
  }, 12, monthFromEnum, Data_Enum.defaultPred(monthToEnum)(monthFromEnum), Data_Enum.defaultSucc(monthToEnum)(monthFromEnum), monthToEnum);
  exports["January"] = January;
  exports["February"] = February;
  exports["March"] = March;
  exports["April"] = April;
  exports["May"] = May;
  exports["June"] = June;
  exports["July"] = July;
  exports["August"] = August;
  exports["September"] = September;
  exports["October"] = October;
  exports["November"] = November;
  exports["December"] = December;
  exports["Year"] = Year;
  exports["now"] = now;
  exports["semiringYear"] = semiringYear;
  exports["ringYear"] = ringYear;
  exports["boundedMonth"] = boundedMonth;
  exports["enumMonth"] = enumMonth;;
 
})(PS["Data.Date"] = PS["Data.Date"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Date.Locale

  // jshint maxparams: 2
  exports.dateMethod = function (method, date) {
    return function () {
      return date[method]();
    };
  };
 
})(PS["Data.Date.Locale"] = PS["Data.Date.Locale"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.Date.Locale"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_Date = PS["Data.Date"];
  var Data_Enum = PS["Data.Enum"];
  var Data_Function = PS["Data.Function"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_Unsafe = PS["Data.Maybe.Unsafe"];
  var Data_Time = PS["Data.Time"];
  var Prelude = PS["Prelude"];     
  var year = function (d) {
      return $foreign.dateMethod("getFullYear", d);
  };
  var toLocaleDateString = function (d) {
      return $foreign.dateMethod("toLocaleDateString", d);
  };
  var month = function (d) {
      return Prelude["<$>"](Control_Monad_Eff.functorEff)(function (_0) {
          return Data_Maybe_Unsafe.fromJust(Data_Enum.toEnum(Data_Date.enumMonth)(_0));
      })($foreign.dateMethod("getMonth", d));
  };
  var dayOfMonth = function (d) {
      return $foreign.dateMethod("getDate", d);
  };
  exports["toLocaleDateString"] = toLocaleDateString;
  exports["dayOfMonth"] = dayOfMonth;
  exports["month"] = month;
  exports["year"] = year;;
 
})(PS["Data.Date.Locale"] = PS["Data.Date.Locale"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Int

  exports.fromNumberImpl = function (just) {
    return function (nothing) {
      return function (n) {
        /* jshint bitwise: false */
        return (n | 0) === n ? just(n) : nothing;
      };
    };
  };

  exports.toNumber = function (n) {
    return n;
  };
 
})(PS["Data.Int"] = PS["Data.Int"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  exports.ceil = Math.ceil;

  exports.floor = Math.floor;

  exports["%"] = function(n) {
    return function(m) {
      return n % m;
    };
  };                         
 
})(PS["Math"] = PS["Math"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Math"];
  exports["%"] = $foreign["%"];
  exports["floor"] = $foreign.floor;
  exports["ceil"] = $foreign.ceil;;
 
})(PS["Math"] = PS["Math"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var $foreign = PS["Data.Int"];
  var Prelude = PS["Prelude"];
  var Data_Int_Bits = PS["Data.Int.Bits"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_Unsafe = PS["Data.Maybe.Unsafe"];
  var $$Math = PS["Math"];                                                                   
  var fromNumber = $foreign.fromNumberImpl(Data_Maybe.Just.create)(Data_Maybe.Nothing.value);
  var unsafeClamp = function (x) {
      if (x >= $foreign.toNumber(Prelude.top(Prelude.boundedInt))) {
          return Prelude.top(Prelude.boundedInt);
      };
      if (x <= $foreign.toNumber(Prelude.bottom(Prelude.boundedInt))) {
          return Prelude.bottom(Prelude.boundedInt);
      };
      if (Prelude.otherwise) {
          return Data_Maybe_Unsafe.fromJust(fromNumber(x));
      };
      throw new Error("Failed pattern match at Data.Int line 48, column 1 - line 49, column 1: " + [ x.constructor.name ]);
  };
  var floor = function (_2) {
      return unsafeClamp($$Math.floor(_2));
  };
  var ceil = function (_3) {
      return unsafeClamp($$Math.ceil(_3));
  };
  exports["floor"] = floor;
  exports["ceil"] = ceil;
  exports["fromNumber"] = fromNumber;
  exports["toNumber"] = $foreign.toNumber;;
 
})(PS["Data.Int"] = PS["Data.Int"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_Date = PS["Data.Date"];
  var Data_Date_Locale = PS["Data.Date.Locale"];
  var Data_Enum = PS["Data.Enum"];
  var Data_Int = PS["Data.Int"];
  var $$Math = PS["Math"];
  var Prelude = PS["Prelude"];     
  var priorElapsedDays = function (year) {
      var p = Data_Int.toNumber(year - 1);
      return (((Data_Int.floor(p) * 365 | 0) + Data_Int.floor(p / 4.0) | 0) - Data_Int.floor(p / 100.0)) + Data_Int.floor(p / 400.0) | 0;
  };
  var isLeap = function (year) {
      var y = Data_Int.toNumber(year);
      return $$Math["%"](y)(4.0) === 0.0 && ($$Math["%"](y)(100.0) !== 0.0 || $$Math["%"](y)(400.0) === 0.0);
  };
  var deductLeapDays = function (year) {
      return function (days) {
          var _5 = isLeap(year);
          if (_5) {
              return days - 1;
          };
          if (!_5) {
              return days - 2;
          };
          throw new Error("Failed pattern match at Data.Date.Gregorian line 21, column 1 - line 22, column 1: " + [ _5.constructor.name ]);
      };
  };
  var ordinalDays = function (year) {
      return function (month) {
          return function (day) {
              var monthInt = Data_Enum.fromEnum(Data_Date.enumMonth)(month) + 1 | 0;
              var ordinal = Data_Int.floor(Data_Int.toNumber((367 * monthInt | 0) - 362) / 12.0) + day | 0;
              var _7 = monthInt > 2;
              if (_7) {
                  return deductLeapDays(year)(ordinal);
              };
              if (!_7) {
                  return ordinal;
              };
              throw new Error("Failed pattern match at Data.Date.Gregorian line 28, column 1 - line 29, column 1: " + [ _7.constructor.name ]);
          };
      };
  };
  var toFixed = function (date) {
      return function __do() {
          var _2 = Data_Date_Locale.year(date)();
          var _1 = Data_Date_Locale.month(date)();
          var _0 = Data_Date_Locale.dayOfMonth(date)();
          return Prelude["return"](Control_Monad_Eff.applicativeEff)(priorElapsedDays(_2) + ordinalDays(_2)(_1)(_0) | 0)();
      };
  };
  exports["isLeap"] = isLeap;
  exports["toFixed"] = toFixed;
  exports["priorElapsedDays"] = priorElapsedDays;
  exports["ordinalDays"] = ordinalDays;
  exports["deductLeapDays"] = deductLeapDays;;
 
})(PS["Data.Date.Gregorian"] = PS["Data.Date.Gregorian"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Data_Date = PS["Data.Date"];
  var Data_Int = PS["Data.Int"];
  var $$Math = PS["Math"];
  var Prelude = PS["Prelude"];     
  var symNewYearDay = function (year) {
      var p = year - 1;
      return (1 + (364 * p | 0) | 0) + ((7 * ((52 * p | 0) + 146 | 0) | 0) / 293 | 0) | 0;
  };
  var symMonthToDay = function (dayOfYear) {
      return function (month) {
          var daysBefore = ((28 * month | 0) + ((7 * month | 0) / 3 | 0) | 0) - 28;
          return dayOfYear - daysBefore;
      };
  };
  var symDayToMonth = function (dayOfYear) {
      var weekOfYear = Data_Int.ceil(Data_Int.toNumber(dayOfYear) / 7.0);
      var quarter = Data_Int.ceil((4.0 / 53.0) * Data_Int.toNumber(weekOfYear));
      var dayOfQuarter = dayOfYear - (91 * (quarter - 1) | 0);
      var weekOfQuarter = Data_Int.ceil(Data_Int.toNumber(dayOfQuarter) / 7.0);
      var monthOfQuarter = Data_Int.ceil((2.0 / 9.0) * Data_Int.toNumber(weekOfQuarter));
      return ((3 * quarter | 0) + monthOfQuarter | 0) - 3;
  };
  var estimateSymYear = function (fixed) {
      var f = Data_Int.toNumber(fixed);
      return Data_Date.Year(Data_Int.ceil((f - 1.0) / (365.0 + 71.0 / 293.0)));
  };
  var checkForLeapWeek = function (fixed) {
      return function (start) {
          var nextYear = Prelude["+"](Data_Date.semiringYear)(estimateSymYear(fixed))(1);
          var _2 = fixed - start >= 364 && fixed >= symNewYearDay(nextYear);
          if (_2) {
              return nextYear;
          };
          if (!_2) {
              return estimateSymYear(fixed);
          };
          throw new Error("Failed pattern match at Data.Date.Symmetry454 line 21, column 1 - line 22, column 1: " + [ _2.constructor.name ]);
      };
  };
  var fixedToSymYear = function (fixed) {
      return function (start) {
          if (fixed < start) {
              return Prelude["-"](Data_Date.ringYear)(estimateSymYear(fixed))(1);
          };
          if (fixed > start) {
              return checkForLeapWeek(fixed)(start);
          };
          if (Prelude.otherwise) {
              return estimateSymYear(fixed);
          };
          throw new Error("Failed pattern match at Data.Date.Symmetry454 line 53, column 1 - line 54, column 1: " + [ fixed.constructor.name, start.constructor.name ]);
      };
  };
  var fixedToSym = function (fixed) {
      var year = fixedToSymYear(fixed)(symNewYearDay(estimateSymYear(fixed)));
      var yearString = Prelude.show(Prelude.showInt)(year);
      var dayOfYear = (fixed - symNewYearDay(year)) + 1 | 0;
      var month = symDayToMonth(dayOfYear);
      var day = symMonthToDay(dayOfYear)(month);
      return Prelude.show(Prelude.showInt)(month) + ("/" + (Prelude.show(Prelude.showInt)(day) + ("/" + yearString)));
  };
  exports["symNewYearDay"] = symNewYearDay;
  exports["symMonthToDay"] = symMonthToDay;
  exports["symDayToMonth"] = symDayToMonth;
  exports["fixedToSymYear"] = fixedToSymYear;
  exports["fixedToSym"] = fixedToSym;
  exports["estimateSymYear"] = estimateSymYear;
  exports["checkForLeapWeek"] = checkForLeapWeek;;
 
})(PS["Data.Date.Symmetry454"] = PS["Data.Date.Symmetry454"] || {});
(function(exports) {
  // Generated by psc version 0.7.6.1
  "use strict";
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_Date = PS["Data.Date"];
  var Data_Date_Gregorian = PS["Data.Date.Gregorian"];
  var Data_Date_Locale = PS["Data.Date.Locale"];
  var Data_Date_Symmetry454 = PS["Data.Date.Symmetry454"];
  var Data_DOM_Simple_Unsafe_Element = PS["Data.DOM.Simple.Unsafe.Element"];
  var Data_DOM_Simple_Unsafe_Window = PS["Data.DOM.Simple.Unsafe.Window"];
  var Data_DOM_Simple_Window = PS["Data.DOM.Simple.Window"];
  var DOM = PS["DOM"];
  var Prelude = PS["Prelude"];     
  var querySelector = function (query) {
      return Prelude[">>="](Control_Monad_Eff.bindEff)(Data_DOM_Simple_Unsafe_Window.unsafeDocument(Data_DOM_Simple_Window.globalWindow))(Data_DOM_Simple_Unsafe_Element.unsafeQuerySelector(query));
  };
  var main = function __do() {
      var _1 = Prelude[">>="](Control_Monad_Eff.bindEff)(Data_Date.now)(Data_Date_Locale.toLocaleDateString)();
      var _0 = Prelude[">>="](Control_Monad_Eff.bindEff)(Data_Date.now)(Data_Date_Gregorian.toFixed)();
      Prelude[">>="](Control_Monad_Eff.bindEff)(querySelector("#gregorian"))(Data_DOM_Simple_Unsafe_Element.unsafeSetTextContent(_1))();
      return Prelude[">>="](Control_Monad_Eff.bindEff)(querySelector("#symmetry454"))(Data_DOM_Simple_Unsafe_Element.unsafeSetTextContent(Data_Date_Symmetry454.fixedToSym(_0)))();
  };
  exports["querySelector"] = querySelector;
  exports["main"] = main;;
 
})(PS["Main"] = PS["Main"] || {});

PS["Main"].main();
